name: Generate Resume PDF and Deploy

on:
  schedule:
    - cron: "30 18 * * *"

jobs:
  send-mail:
    runs-on: ubuntu-latest

    env:
      MAIL: ${{secrets.MAIL}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Updates
        run: |
          last_commit_time=$(git log -1 --format="%at")
          current_time=$(date +%s)
          time_diff=$((current_time - last_commit_time))

          if [ $time_diff -le 86400 ]; then
              cd api && npm install && node generatePdf.js && node sendMail.js $MAIL
          else
            echo "No updates in the last 24 hours. Exiting without running the job."
          fi
